name: Nightly Release

on:
  schedule:
    - cron:  '0 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install requirements
      run: |
        pip install -r dev-requirements.txt
    - name: Build Package
      env: 
        ALLENNLP_VERSION: $(git rev-parse --short "$GITHUB_SHA")
      run: |
        python setup.py bdist_wheel sdist
    - name: Test Packages
      run: |
        pip install $(ls dist/*.whl)
        allennlp test-install
    - name: Deploy
      run: |
        twine upload -u ${{ secrets.PYPI_NIGHTLY_USERNAME }} -p ${{ secrets.PYPI_NIGHTLY_PASSWORD }} dist/*
        rm -rf dist/
